---
- import_playbook: ../common-packer/provision/baseline.yaml
- hosts: all
  become_user: root
  become_method: sudo

  tasks:
    - name: Install pre-requisites
      yum:
        name:
          - gcc
          - gcc-c++
          - make
        state: present
      become: true

    - name: Add nodejs repo
      # yamllint disable-line rule:line-length
      shell: curl --silent --location https://rpm.nodesource.com/setup_14.x | sudo bash -

    - name: Install nodejs
      yum:
        name: nodejs
        state: present
      when: ansible_distribution == 'CentOS'
      become: true
